# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'QTRadio' do

  pod 'SnapKit', '~> 4.0.0'
  pod 'Alamofire'
  pod 'Kingfisher'
  pod 'Reveal-SDK', :configurations => ['Debug']

end
